/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import Entidades.*;
import AccesoADatos.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CDR
 */
public class ConsultarVentas extends javax.swing.JInternalFrame {

    private DefaultTableModel tobleron;
    private ProductoData proData;
    private List<Venta> ventas;
    private VentaData venData;
    private Venta ventaActual;
    private DetalleVentaData detVenData;
    private DetalleVenta detVenta;
    private ClienteData clienData;
    /**
     * Creates new form ConsultarVentas
     */
    public ConsultarVentas() {
        initComponents();
        setTitle("Listado de ventas");
//        setResizable(false);

        tobleron = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int fila, int columna){
                return false;
            }
        };
        
        proData = new ProductoData();
        clienData = new ClienteData();
        detVenData = new DetalleVentaData();
        ventaActual = new Venta();
        ventas = new ArrayList<>();
        detVenta = new DetalleVenta();
        venData = new VentaData();
        generarTablin();
        accederTablin();
        
    }
    
    private void generarTablin(){
        
        ArrayList<Object> columna = new ArrayList<>();
        
        columna.add("ID");
        columna.add("FECHA");
        columna.add("PRODUCTO");
        columna.add("CANTIDAD");
        columna.add("PRECIO");
        columna.add("NOMBRE");
        columna.add("APELLIDO");
        columna.add("TELEFONO");
        
        for (Object columnas : columna){
            tobleron.addColumn(columnas);
        }
        
        jtblVentas.setModel(tobleron);
    }
    
    private void accederTablin(){
        
        ventas = venData.obtenerVentas();
        
        for (Venta vendin : ventas){
            Cliente clien = clienData.buscarCliente(vendin.getCliente().getIdCliente());
            DetalleVenta detVendin = detVenData.listarDetalleVenta(vendin.getIdVenta());
            
            tobleron.addRow(new Object[]{
                vendin.getIdVenta(),
                vendin.getFecha(), 
                detVendin.getProducto().getNombre(),
                detVendin.getCantidad(), 
                detVendin.getPrecioVenta(),
                clien.getNombre(),
                clien.getApellido(),
                clien.getTelefono(), 
                });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jtblVentas = new javax.swing.JTable();
        jbtSalir = new javax.swing.JButton();

        setResizable(true);

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitulo.setText("Listado de ventas");

        jtblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane.setViewportView(jtblVentas);

        jbtSalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbtSalir.setText("Salir");
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtSalir)
                        .addGap(35, 35, 35)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbtSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton jbtSalir;
    private javax.swing.JTable jtblVentas;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
